# Processed individual photons file
input_single_photons: './combined_data.csv'

n_events: 10000 # events to generate
integration_window: 100.e-9 # seconds
seed: 1 # Set random seed. If 0 is passed, then the seed is not fixed
